name: Docker

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 28-31 * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  latest:
    name: Latest
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Debian push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: debian/Dockerfile
          push: true
          tags: |
            buzzxu/docker:debian
            ghcr.io/buzzxu/docker:debian
      -
        name: Alpine push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: alpine/Dockerfile
          push: true
          tags: |
            buzzxu/docker:alpine
            ghcr.io/buzzxu/docker:alpine
